### PR TITLE
Added specular and opacity to Matte material

### PR DESCRIPTION
**Pull request by mvictoras**
Matte material was missing specular and opacity.

### CODE REVIEW

**Review by johguenther — COMMENTED** [review]
Thanks for the fix adding the missing `opacity` parameter!

**Comment by mvictoras** [comment]
Fixed: Removed specular and specularColor and updated color's default value.

**Review by johguenther — APPROVED** [review]
Thanks!

**Comment by johguenther** [comment]
Squashed and merged manually (it is not possible with GH web UI to get a proper linear history).

**Pull request closed without merging**
